'use client';
import { FormEvent, useState } from 'react';
import { MessageCircleHeart, Send } from 'lucide-react';
import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';
import { EmptyState } from '@/components/ui/EmptyState';
import { SectionTitle } from '@/components/ui/SectionTitle';
import { initialTributes } from '@/data/memorial';
import type { Tribute } from '@/types/memorial';
export function Tributes() { const [tributes,setTributes]=useState<Tribute[]>(initialTributes); const [name,setName]=useState(''); const [message,setMessage]=useState(''); const [status,setStatus]=useState('');
function submit(e:FormEvent){ e.preventDefault(); const cleanName=name.trim(), cleanMessage=message.trim(); if(!cleanName || !cleanMessage){ setStatus('Preencha seu nome e sua mensagem.'); return; } setTributes((curr)=>[{id:crypto.randomUUID(),author:cleanName,message:cleanMessage,createdAt:'Agora'},...curr]); setName(''); setMessage(''); setStatus('Tributo adicionado nesta demonstração.'); }
return <section id="tributos" className="scroll-mt-24"><SectionTitle eyebrow="Tributos & Condolências" title="Palavras que permanecem" description="Deixe uma mensagem de carinho ou uma lembrança."/><div className="grid gap-5 lg:grid-cols-[1.4fr_.9fr]"><div className="space-y-3">{tributes.length===0?<EmptyState>Ainda não há tributos.</EmptyState>:tributes.map((t)=><Card key={t.id} className="p-5"><MessageCircleHeart className="h-5 w-5 text-[var(--sage-dark)]"/><p className="mt-3 text-sm leading-6 text-[#535950]">“{t.message}”</p><div className="mt-4 flex items-center justify-between text-xs text-[var(--warm-gray)]"><span>— {t.author}</span><span>{t.createdAt}</span></div></Card>)}</div><Card className="h-fit p-5 sm:p-6"><form onSubmit={submit} noValidate><h3 className="font-display text-xl">Compartilhe uma lembrança</h3><label className="mt-5 block text-sm font-medium">Nome<input value={name} onChange={(e)=>setName(e.target.value)} className="mt-2 min-h-11 w-full rounded-2xl border border-[var(--border)] bg-white px-4 text-sm outline-none focus:border-[var(--sage)] focus:ring-2 focus:ring-[#dfe6da]" name="name" autoComplete="name"/></label><label className="mt-4 block text-sm font-medium">Mensagem<textarea value={message} onChange={(e)=>setMessage(e.target.value)} className="mt-2 min-h-32 w-full resize-y rounded-2xl border border-[var(--border)] bg-white px-4 py-3 text-sm outline-none focus:border-[var(--sage)] focus:ring-2 focus:ring-[#dfe6da]" name="message"/></label>{status && <p className="mt-3 text-xs text-[var(--sage-dark)]" role="status">{status}</p>}<Button className="mt-4 w-full" type="submit"><Send className="h-4 w-4"/>Publicar tributo</Button><p className="mt-3 text-xs leading-5 text-[var(--warm-gray)]">Nesta primeira versão, a mensagem fica apenas no estado local do navegador.</p></form></Card></div></section>; }
